### PR TITLE
Created HTML and CSS files for Template 27

### PR DESCRIPTION
**Pull request by mt-evarest**

### CODE REVIEW

**Comment by frankhart2018** [comment]
@mt-evarest please update the placeholder "sample bullets" in projects to jinja2 template format with appropriate variable name. Also remove the leadership part. Thanks.

**Comment by mt-evarest** [comment]
@frankhart2018 Sorry missed that. The second 'Project' is supposed to be 'Extra Curricular Activities' is that still needed?

**Comment by frankhart2018** [comment]
No all projects are supposed to be projects only not extra curricular activites. Refer to some examples that are already there in our repository @mt-evarest.

**Comment by mt-evarest** [comment]
@frankhart2018 As mentioned before, I already added a Project section. The second 'Project' was the wrong heading and it is 'Extra Curricular Activities', which is what the template pdf has

**Comment by frankhart2018** [comment]
Make it projects instead of extra curricular activities

**Pull request closed without merging**
