### PR TITLE
add template 6, issue 23

### PR DESCRIPTION
**Pull request by hendraaagil**

### CODE REVIEW

**Review by dhairyaj — CHANGES_REQUESTED** [review]
CSS FIle seems okay but changes are required in the HTML file. Refer to the format.txt file in static/resume_templates/format for the updated handlebars

**Comment by hendraaagil** [comment]
> CSS FIle seems okay but changes are required in the HTML file. Refer to the format.txt file in static/resume_templates/format for the updated handlebars

okay, I will fix that

**Review by dhairyaj — APPROVED** [review]
Good work @hendraaagil . Thanks for your Contribution

**Comment by dhairyaj** [comment]
Thanks @hendraaagil for contributing

**Comment by hendraaagil** [comment]
> Thanks @hendraaagil for contributing

You're welcome

**Pull request merged**
